# Generated by Django 5.0.6 on 2024-08-25 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('configurations', '0002_rename_currencies_currency_rename_languages_language'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserSettings',
            new_name='UserSetting',
        ),
    ]
