# Generated by Django 5.0.6 on 2024-07-30 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='user_agent',
            field=models.TextField(null=True),
        ),
    ]
