# Generated by Django 5.0.6 on 2024-08-18 11:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_device_user_agent'),
        ('configurations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('INTERNAL', 'internal'), ('EXTERNAL', 'external')], db_index=True, default='INTERNAL', max_length=15),
        ),
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_currency', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='configurations.currencies')),
                ('preferred_language', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='configurations.languages')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
