# Generated by Django 5.0.6 on 2024-08-25 13:27

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import properties.models.profiles
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('configurations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statuses', models.JSONField(default=properties.models.profiles.Profiles.default_statuses)),
                ('boundary', django.contrib.gis.db.models.fields.PolygonField(geography=True, srid=4326)),
                ('central_coordinate', models.JSONField()),
                ('location_name', models.CharField(blank=True, max_length=255, null=True)),
                ('user_type', models.CharField(choices=[('COMPANY', 'Company'), ('INDIVIDUAL', 'Individual')], db_index=True, default='INDIVIDUAL', max_length=15)),
                ('name', models.CharField(blank=True, max_length=70, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.userprofile')),
            ],
            options={
                'verbose_name': 'LaLouge Estate User Profile',
                'verbose_name_plural': 'LaLouge Estate User Profiles',
            },
        ),
        migrations.CreateModel(
            name='Properties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('age', models.DateField()),
                ('availability', models.CharField(choices=[('for_rent', 'For Rent'), ('for_sale', 'For Sale'), ('sold', 'Sold'), ('rented', 'Rented'), ('under_offer', 'Under Offer'), ('pending_sale', 'Pending Sale'), ('for_lease', 'For Lease'), ('available', 'Available'), ('reserved', 'Reserved'), ('off_market', 'Off Market'), ('coming_soon', 'Coming Soon'), ('auction', 'Auction'), ('not_available', 'Not Available'), ('pre_sold', 'Pre-Sold'), ('for_trade', 'For Trade'), ('under_renovation', 'Under Renovation'), ('pre_rental', 'Pre-Rental'), ('for_sublet', 'For Sublet')], default='not_available', max_length=50)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('exchange_rate_from_usd_upon_upload', models.DecimalField(decimal_places=2, max_digits=10)),
                ('number_of_shares', models.IntegerField(default=0)),
                ('number_of_views', models.IntegerField(default=0)),
                ('built_on', models.DateField()),
                ('uploaded_on', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='configurations.currencies')),
            ],
            options={
                'verbose_name': 'Property',
                'verbose_name_plural': 'Properties',
            },
        ),
    ]
