# Generated by Django 5.0.6 on 2024-08-25 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('configurations', '0001_initial'),
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Currencies',
            new_name='Currency',
        ),
        migrations.RenameModel(
            old_name='Languages',
            new_name='Language',
        ),
    ]
